name: 'MyAction'
description: 'Say hello to a user or the world.'
inputs:
  who-to-greet:
    description: 'Who to greet in the log'
    required: true
    default: 'World'
    type: string
outputs:
  time:
      escription: 'The time we said hello.'
runs:
    using: 'docker'
    image: 'Dockerfile'
    args:
      - ${{ inputs.who-to-greet }}
